# Generated by Django 3.1.3 on 2020-12-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='audio_song',
            field=models.FileField(default='', editable=False, upload_to='media/'),
        ),
    ]
