# Generated by Django 3.1.3 on 2020-12-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_songs_audio_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='album_cover',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/cover_image'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='audio_song',
            field=models.FileField(default='', upload_to='media/songs'),
        ),
    ]
