# Generated by Django 3.1.3 on 2020-12-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
