# Generated by Django 3.1.3 on 2020-12-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_post_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='note',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
