# Generated by Django 3.1.3 on 2020-12-24 14:13

from django.db import migrations, models
import song.models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0009_auto_20201224_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='audio_song',
            field=models.FileField(default='', upload_to='media/songs', validators=[song.models.validate_file_extension]),
        ),
    ]
