# Generated by Django 3.1.3 on 2021-01-15 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0010_auto_20201224_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='admin',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
