# Generated by Django 3.1.3 on 2021-01-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0016_auto_20210115_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='song.acousticuser'),
        ),
    ]
