# Generated by Django 3.1.3 on 2021-01-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0021_auto_20210115_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='username',
        ),
    ]
