# Generated by Django 3.1.3 on 2021-01-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0022_auto_20210115_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='author',
        ),
    ]
