# Generated by Django 3.1.3 on 2021-01-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0023_auto_20210115_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
