# Generated by Django 3.1.3 on 2021-01-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0024_auto_20210115_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
